"""create judgment_metadata table

Revision ID: 3e2cd3b29d46
Revises: 
Create Date: 2026-05-19 18:50:58.751736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2cd3b29d46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgment_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doctype', sa.Integer(), nullable=True),
    sa.Column('docsource', sa.String(), nullable=True),
    sa.Column('catids', sa.String(), nullable=True),
    sa.Column('authorid', sa.String(), nullable=True),
    sa.Column('bench', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('numcites', sa.Integer(), nullable=True),
    sa.Column('numcitedby', sa.Integer(), nullable=True),
    sa.Column('docsize', sa.Integer(), nullable=True),
    sa.Column('fragment', sa.Boolean(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tid')
    )
    op.create_index(op.f('ix_judgment_metadata_id'), 'judgment_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgment_metadata_id'), table_name='judgment_metadata')
    op.drop_table('judgment_metadata')
    # ### end Alembic commands ###
