"""add courts table and judgment court relation

Revision ID: 9b567f21bd98
Revises: 3e2cd3b29d46
Create Date: 2026-05-20 20:12:03.707531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b567f21bd98'
down_revision: Union[str, None] = '3e2cd3b29d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('court_type', sa.String(), nullable=False),
    sa.Column('jurisdiction_level', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_court_name_country')
    )
    op.create_index(op.f('ix_courts_id'), 'courts', ['id'], unique=False)
    op.add_column('judgment_metadata', sa.Column('court_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_judgment_metadata_court_id'), 'judgment_metadata', ['court_id'], unique=False)
    op.create_foreign_key(None, 'judgment_metadata', 'courts', ['court_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judgment_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_judgment_metadata_court_id'), table_name='judgment_metadata')
    op.drop_column('judgment_metadata', 'court_id')
    op.drop_index(op.f('ix_courts_id'), table_name='courts')
    op.drop_table('courts')
    # ### end Alembic commands ###
